Repository krud-dev/ostara, pull requests merged in 2023-07, with the labels that each got.

#659 fix: app updater quit and install not working
  .changeset/poor-humans-film.md
  app/src/infra/autoupdate/appUpdater.ts
Labels: bug

#665 fix: agent test connection
  app/src/renderer/apis/apiKeys.ts
  app/src/renderer/apis/requests/actuator/testConnectionByUrl.ts
  app/src/renderer/apis/requests/agent/getAgentInfoByUrl.ts
  app/src/renderer/apis/requests/crud/entity/entities/stub.crudEntity.ts
  app/src/renderer/apis/requests/crud/entity/entity.d.ts
  app/src/renderer/components/item/authentication/effective/EffectiveAuthenticationDetails.tsx
  app/src/renderer/components/item/dialogs/forms/AgentDetailsForm.tsx
Labels: bug

#667 feat: app updater improvements @avivm
  .changeset/orange-planets-hope.md
  app/src/infra/autoupdate/appUpdater.ts
  app/src/infra/autoupdate/main.ts
  app/src/infra/autoupdate/renderer.ts
  app/src/infra/autoupdate/types.d.ts
  app/src/infra/store/renderer.ts
  app/src/infra/store/store.ts
  app/src/infra/store/types.d.ts
  app/src/renderer/apis/requests/crud/entity/entity.d.ts
  app/src/renderer/components/managers/AppUpdatesManager.tsx
  app/src/renderer/contexts/AppUpdatesContext.tsx
  app/src/renderer/lang/locales/en_US.ts
  app/src/renderer/pages/settings/general/index.tsx
  app/src/renderer/theme/overrides/Link.ts
Labels: enhancement

#676 fix: agents ui bugs
  app/src/renderer/contexts/ItemsContext.tsx
  app/src/renderer/lang/locales/en_US.ts
  app/src/renderer/layout/agent/components/health/AgentUnhealthy.tsx
  app/src/renderer/layout/navigator/components/sidebar/tree/menus/items/RunDiscoveryMenuItem.tsx
  app/src/renderer/pages/navigator/application/dashboard/index.tsx
Labels: bug

#677 fix: health notifications generators bugs
  app/src/renderer/components/managers/notifications/generators/NotificationsGeneratorAgentHealth.tsx
  app/src/renderer/components/managers/notifications/generators/NotificationsGeneratorApplicationHealth.tsx
Labels: bug

#693 feat: add agent creation wizard
  app/src/renderer/components/item/dialogs/create/CreateAgentDialog.tsx
  app/src/renderer/components/item/dialogs/forms/AgentDetailsForm.tsx
  app/src/renderer/components/layout/TabPanel.tsx
  app/src/renderer/components/layout/stepper/StepperContext.tsx
  app/src/renderer/components/layout/stepper/StepperPanel.tsx
  app/src/renderer/constants/ui.ts
  app/src/renderer/lang/locales/en_US.ts
  app/src/renderer/theme/overrides/Dialog.ts
Labels: enhancement

#701 fix: navigator tree select item crash
  app/src/renderer/layout/navigator/components/sidebar/tree/NavigatorTree.tsx
Labels: bug

#703 fix: restore backup crash
  app/src/renderer/layout/navigator/components/sidebar/tree/NavigatorTreePreview.tsx
  app/src/renderer/layout/navigator/components/sidebar/tree/nodes/NavigatorTreeNodeBase.tsx
  app/src/renderer/layout/navigator/components/sidebar/tree/nodes/NavigatorTreeNodePreview.tsx
Labels: bug

#704 fix: add agent to invalidate queries on restore backup
  app/src/renderer/apis/requests/backup/importBackup.ts
  app/src/renderer/apis/requests/system-backup/restoreSystemBackup.ts
Labels: bug

#709 chore: versioning changes
  .github/actions/determine-version/action.yml
  .github/workflows/publish-spring-client.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  app/package-lock.json
  app/package.json
  app/release/app/package-lock.json
  app/release/app/package.json
  daemon/build.gradle.kts
  demo/build.gradle.kts
  package-lock.json
  package.json
  spring-client/build.gradle.kts
Labels: ci-do-release
