Repository krud-dev/ostara, pull requests merged in 2023-06, with the labels that each got.

#477 fix: ui bugs in tables and dashboards
  app/src/main/main.ts
  app/src/renderer/components/common/ToolbarButton.tsx
  app/src/renderer/components/item/logger/LogLevelToggleGroup.tsx
  app/src/renderer/components/table/TableRowCustom.tsx
  app/src/renderer/lang/locales/en_US.ts
  app/src/renderer/pages/navigator/application/dashboard/components/ApplicationInstanceWidget.tsx
  app/src/renderer/pages/navigator/folder/dashboard/components/FolderApplicationWidget.tsx
  app/src/renderer/pages/navigator/folder/dashboard/index.tsx
  app/src/renderer/pages/navigator/home/components/HomeDeveloperMode.tsx
Labels: bug

#479 feat: add folders and metric rules to developer mode data generation
  app/src/renderer/pages/navigator/home/components/HomeDeveloperMode.tsx
Labels: enhancement

#489 feat: add notifications settings
  .changeset/eighty-terms-love.md
  app/src/infra/notifications/models/notificationInfo.ts
  app/src/infra/notifications/notificationsService.ts
  app/src/renderer/components/managers/NotificationsManager.tsx
  app/src/renderer/contexts/SettingsContext.tsx
  app/src/renderer/lang/locales/en_US.ts
  app/src/renderer/layout/common/main-sidebar/navbar/SettingsMenu.tsx
  app/src/renderer/pages/navigator/home/components/HomeDeveloperMode.tsx
Labels: enhancement

#491 feat: select item on creation
  .changeset/warm-poems-vanish.md
  app/src/renderer/components/item/dialogs/create/CreateApplicationDialog.tsx
  app/src/renderer/components/item/dialogs/create/CreateFolderDialog.tsx
  app/src/renderer/components/item/dialogs/create/CreateInstanceDialog.tsx
  app/src/renderer/contexts/ItemsContext.tsx
  app/src/renderer/layout/navigator/components/sidebar/menus/CreateItemMenuItems.tsx
  app/src/renderer/layout/navigator/components/sidebar/tree/NavigatorTree.tsx
  app/src/renderer/layout/navigator/components/sidebar/tree/menus/items/AddApplicationMenuItem.tsx
  app/src/renderer/layout/navigator/components/sidebar/tree/menus/items/AddFolderMenuItem.tsx
  app/src/renderer/layout/navigator/components/sidebar/tree/menus/items/AddInstanceMenuItem.tsx
  app/src/renderer/pages/navigator/application/dashboard/index.tsx
  app/src/renderer/pages/navigator/folder/dashboard/index.tsx
  app/src/renderer/pages/navigator/home/components/HomeGettingStarted.tsx
  app/src/renderer/pages/navigator/home/components/HomeWelcome.tsx
Labels: enhancement

#499 feat: add predefined metric rules suggestions
  app/src/renderer/components/widget/card/DashboardGenericCard.tsx
  app/src/renderer/entity/entities/applicationMetricRule.entity.tsx
  app/src/renderer/lang/locales/en_US.ts
  app/src/renderer/layout/instance/components/InstanceActiveProfiles.tsx
  app/src/renderer/layout/navigator/components/sidebar/dialogs/ExportConfigurationDialog.tsx
  app/src/renderer/layout/navigator/components/sidebar/dialogs/ImportConfigurationDialog.tsx
  app/src/renderer/pages/navigator/application/metric-rules/components/ApplicationMetricRulesTable.tsx
  app/src/renderer/pages/navigator/application/metric-rules/components/PredefinedMetricRulesButton.tsx
  app/src/renderer/pages/navigator/application/metric-rules/index.tsx
  app/src/renderer/utils/metricUtils.ts
Labels: enhancement

#502 fix: hide notifications sound from settings if notifications are inactive
  app/src/renderer/layout/common/main-sidebar/navbar/SettingsMenu.tsx
Labels: bug

#504 fix: change folder dashboard paths to relative of selected folder
  app/src/renderer/pages/navigator/folder/dashboard/index.tsx
  app/src/renderer/utils/treeUtils.ts
Labels: bug

#505 fix: folder/application dashboards sorting by tree order
  app/src/renderer/pages/navigator/application/dashboard/index.tsx
  app/src/renderer/pages/navigator/folder/dashboard/index.tsx
Labels: bug

#506 fix: metric and metric rules fixes and improvements
  app/src/renderer/components/managers/NotificationsManager.tsx
  app/src/renderer/entity/entities/applicationMetricRule.entity.tsx
  app/src/renderer/lang/locales/en_US.ts
  app/src/renderer/pages/navigator/application/metric-rules/components/MetricRuleDetailsForm.tsx
  app/src/renderer/pages/navigator/application/metric-rules/components/MetricRuleFormula.tsx
  app/src/renderer/pages/navigator/application/metric-rules/components/MetricSelectionForm.tsx
  app/src/renderer/pages/navigator/instance/metrics/components/MetricDetails.tsx
  app/src/renderer/pages/navigator/instance/metrics/components/MetricDetailsTags.tsx
  app/src/renderer/utils/metricUtils.ts
Labels: bug

#507 chore: update urls help url
  app/src/renderer/routes/urls.ts
Labels: documentation

#519 feat: improve folder-applications and application-instances tables empty states
  .changeset/thick-kangaroos-kneel.md
  app/src/renderer/pages/navigator/application/dashboard/index.tsx
  app/src/renderer/pages/navigator/application/instances/index.tsx
  app/src/renderer/pages/navigator/folder/applications/index.tsx
Labels: enhancement

#520 feat: improve home screen feedback ui
  .changeset/soft-cats-sip.md
  app/src/renderer/components/icons/DiscordIcon.tsx
  app/src/renderer/components/icons/GithubIcon.tsx
  app/src/renderer/lang/locales/en_US.ts
  app/src/renderer/pages/navigator/home/components/HomeDeveloperMode.tsx
  app/src/renderer/pages/navigator/home/components/HomeDocumentation.tsx
  app/src/renderer/pages/navigator/home/components/HomeFeedback.tsx
  app/src/renderer/pages/navigator/home/components/HomeGettingStarted.tsx
  app/src/renderer/pages/navigator/home/components/HomeRepository.tsx
  app/src/renderer/pages/navigator/home/components/HomeWelcome.tsx
  app/src/renderer/pages/navigator/home/index.tsx
Labels: enhancement

#526 feat: add instance info page
  .changeset/chilly-apples-flow.md
  app/src/common/manual_definitions.d.ts
  app/src/renderer/apis/apiKeys.ts
  app/src/renderer/apis/requests/instance/info/getInstanceInfo.ts
  app/src/renderer/components/code/CodeEditor.tsx
  app/src/renderer/components/icons/LinuxIcon.tsx
  app/src/renderer/components/icons/MacOsIcon.tsx
  app/src/renderer/components/icons/WindowsIcon.tsx
  app/src/renderer/lang/locales/en_US.ts
  app/src/renderer/layout/instance/components/InstanceSidebar.tsx
  app/src/renderer/pages/navigator/instance/info/components/InstanceInfoBuild.tsx
  app/src/renderer/pages/navigator/instance/info/components/InstanceInfoExtraValues.tsx
  app/src/renderer/pages/navigator/instance/info/components/InstanceInfoGit.tsx
  app/src/renderer/pages/navigator/instance/info/components/InstanceInfoGitFull.tsx
  app/src/renderer/pages/navigator/instance/info/components/InstanceInfoGitSimple.tsx
  app/src/renderer/pages/navigator/instance/info/components/InstanceInfoGitUnknown.tsx
  app/src/renderer/pages/navigator/instance/info/components/InstanceInfoJava.tsx
  app/src/renderer/pages/navigator/instance/info/components/InstanceInfoJsonCard.tsx
  app/src/renderer/pages/navigator/instance/info/components/InstanceInfoOs.tsx
  app/src/renderer/pages/navigator/instance/info/components/InstanceInfoValuesCard.tsx
  app/src/renderer/pages/navigator/instance/info/index.tsx
  app/src/renderer/routes/routes.tsx
  app/src/renderer/routes/urls.ts
Labels: enhancement

#527 fix: info page components order
  app/src/renderer/pages/navigator/instance/info/index.tsx
Labels: bug

#525 feat: add hint to open os notification settings
  app/src/infra/notifications/main.ts
  app/src/infra/notifications/notificationsService.ts
  app/src/infra/notifications/renderer.ts
  app/src/infra/notifications/types.d.ts
  app/src/renderer/lang/locales/en_US.ts
  app/src/renderer/layout/common/main-sidebar/navbar/SettingsMenu.tsx
Labels: enhancement

#562 feat: add build and git info to instance
  .changeset/slow-books-smoke.md
  app/src/renderer/apis/websockets/stompTopics.ts
  app/src/renderer/components/item/ItemHeader.tsx
  app/src/renderer/components/table/TableComponent.tsx
  app/src/renderer/components/table/TableContext.tsx
  app/src/renderer/components/table/TableHeadCustom.tsx
  app/src/renderer/components/table/TableRowCustom.tsx
  app/src/renderer/contexts/ItemsContext.tsx
  app/src/renderer/entity/entities/applicationInstance.entity.tsx
  app/src/renderer/lang/locales/en_US.ts
  app/src/renderer/pages/navigator/application/dashboard/components/ApplicationInstanceWidget.tsx
  app/src/renderer/pages/navigator/application/instances/index.tsx
  app/src/renderer/utils/itemUtils.tsx
Labels: enhancement

#567 feat: add instance health page
  .changeset/rare-parents-smell.md
  app/src/renderer/apis/apiKeys.ts
  app/src/renderer/apis/requests/instance/health/fetchInstanceHealth.ts
  app/src/renderer/apis/requests/instance/health/getInstanceHealth.ts
  app/src/renderer/apis/requests/instance/health/getInstancesHealth.ts
  app/src/renderer/apis/requests/instance/health/updateInstanceHealth.ts
  app/src/renderer/layout/instance/components/InstanceSidebar.tsx
  app/src/renderer/pages/navigator/instance/health/components/InstanceHealthComponentCard.tsx
  app/src/renderer/pages/navigator/instance/health/index.tsx
  app/src/renderer/pages/navigator/instance/health/utils/instanceHealthDetailsFormatters.ts
  app/src/renderer/pages/navigator/instance/info/index.tsx
  app/src/renderer/routes/routes.tsx
  app/src/renderer/routes/urls.ts
  app/src/renderer/utils/formatUtils.ts
Labels: enhancement

#568 feat: add settings page with sections
  .changeset/tender-parrots-turn.md
  app/src/renderer/lang/locales/en_US.ts
  app/src/renderer/layout/common/main-sidebar/navbar/SettingsMenu.tsx
  app/src/renderer/layout/settings/SettingsLayout.tsx
  app/src/renderer/layout/settings/components/SettingsSidebar.tsx
  app/src/renderer/pages/settings/general/index.tsx
  app/src/renderer/pages/settings/notifications/index.tsx
  app/src/renderer/pages/settings/privacy/index.tsx
  app/src/renderer/routes/routes.tsx
  app/src/renderer/routes/urls.ts
Labels: enhancement

#570 feat: add system backups settings ui
  .changeset/ninety-cameras-repeat.md
  app/src/renderer/apis/apiKeys.ts
  app/src/renderer/apis/requests/system-backup/createSystemBackup.ts
  app/src/renderer/apis/requests/system-backup/deleteSystemBackup.ts
  app/src/renderer/apis/requests/system-backup/getSystemBackups.ts
  app/src/renderer/apis/requests/system-backup/restoreSystemBackup.ts
  app/src/renderer/components/table/data/TableCellData.tsx
  app/src/renderer/components/table/data/TableCellDataBoolean.tsx
  app/src/renderer/entity/actions.ts
  app/src/renderer/entity/entities/systemBackup.entity.tsx
  app/src/renderer/entity/entity.d.ts
  app/src/renderer/lang/locales/en_US.ts
  app/src/renderer/layout/navigator/components/sidebar/dialogs/ExportConfigurationDialog.tsx
  app/src/renderer/layout/navigator/components/sidebar/dialogs/ImportConfigurationDialog.tsx
  app/src/renderer/layout/settings/components/SettingsSidebar.tsx
  app/src/renderer/pages/settings/backups/components/RestoreBackupDialog.tsx
  app/src/renderer/pages/settings/backups/index.tsx
  app/src/renderer/routes/routes.tsx
  app/src/renderer/routes/urls.ts
  daemon/.gitignore
  daemon/src/main/kotlin/dev/krud/boost/daemon/backup/SystemBackupService.kt
  daemon/src/main/kotlin/dev/krud/boost/daemon/base/config/AppMainProperties.kt
Labels: enhancement

#576 feat: add metrics value formatting by unit @avivm
  .changeset/seven-rings-occur.md
  app/src/renderer/pages/navigator/instance/metrics/components/MetricDetailsMeasurements.tsx
  app/src/renderer/utils/formatUtils.ts
Labels: enhancement

#577 fix: slowness when navigating from instance dashboard to another page
  .changeset/violet-rockets-tie.md
  app/src/renderer/apis/websockets/StompContext.tsx
  app/src/renderer/components/widget/card/HealthStatusDashboardWidget.tsx
Labels: bug

#580 fix: navigator tree context menu
  app/src/renderer/layout/navigator/components/sidebar/tree/nodes/NavigatorTreeNode.tsx
  app/src/renderer/layout/navigator/components/sidebar/tree/nodes/NavigatorTreeNodeBase.tsx
Labels: bug

#583 feat: add ui animations
  .changeset/slimy-seas-exist.md
  app/package-lock.json
  app/package.json
  app/src/renderer/components/table/TableCustom.tsx
  app/src/renderer/components/table/TableRowCustom.tsx
  app/src/renderer/constants/ui.ts
  app/src/renderer/lang/locales/en_US.ts
  app/src/renderer/pages/navigator/application/dashboard/index.tsx
  app/src/renderer/pages/navigator/folder/dashboard/index.tsx
  app/src/renderer/pages/navigator/home/components/HomeWhatsNew.tsx
  app/src/renderer/pages/navigator/home/index.tsx
  app/src/renderer/pages/navigator/instance/dashboard/index.tsx
  app/src/renderer/pages/navigator/instance/health/index.tsx
  app/src/renderer/pages/navigator/instance/info/index.tsx
  app/src/renderer/pages/settings/general/index.tsx
  app/src/renderer/pages/settings/notifications/index.tsx
  app/src/renderer/pages/settings/privacy/index.tsx
Labels: enhancement

#588 fix: add navigator tree preview empty state
  app/src/renderer/lang/locales/en_US.ts
  app/src/renderer/layout/navigator/components/sidebar/tree/cards/NavigatorTreePreviewCard.tsx
Labels: bug

#589 fix: navigator tree move/rename/delete async methods
  .changeset/odd-buckets-train.md
  app/src/renderer/layout/navigator/components/sidebar/tree/NavigatorTree.tsx
Labels: bug

#590 feat: add logfile page
  .changeset/six-items-fix.md
  app/src/common/generated_definitions.d.ts
  app/src/renderer/apis/apiKeys.ts
  app/src/renderer/apis/requests/instance/logfile/downloadInstanceLogfile.ts
  app/src/renderer/apis/requests/instance/logfile/getInstanceLogfile.ts
  app/src/renderer/components/code/CodeEditor.tsx
  app/src/renderer/components/code/extensions/logLanguageExtension.ts
  app/src/renderer/lang/locales/en_US.ts
  app/src/renderer/layout/instance/components/InstanceSidebar.tsx
  app/src/renderer/pages/navigator/instance/info/index.tsx
  app/src/renderer/pages/navigator/instance/logfile/components/InstanceLogCode.tsx
  app/src/renderer/pages/navigator/instance/logfile/index.tsx
  app/src/renderer/routes/routes.tsx
  app/src/renderer/routes/urls.ts
  app/src/renderer/theme/config/palette.ts
  daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/ActuatorHttpClientImpl.kt
  daemon/src/main/kotlin/dev/krud/boost/daemon/configuration/instance/ability/LogfileAbilityResolver.kt
  daemon/src/main/kotlin/dev/krud/boost/daemon/configuration/instance/enums/InstanceAbility.kt
  demo/.gitignore
  demo/build.gradle.kts
  demo/src/main/kotlin/dev/krud/ostara/inappdemo/log/LogMessageConstructor.kt
  demo/src/main/kotlin/dev/krud/ostara/inappdemo/log/LogRunner.kt
  demo/src/main/resources/application.properties
Labels: enhancement

#598 feat: add refresh and auto refresh to instance info and health pages
  app/src/renderer/constants/ui.ts
  app/src/renderer/pages/navigator/application/dashboard/index.tsx
  app/src/renderer/pages/navigator/instance/health/components/InstanceHealthComponentCard.tsx
  app/src/renderer/pages/navigator/instance/health/index.tsx
  app/src/renderer/pages/navigator/instance/info/components/InstanceInfoJsonCard.tsx
  app/src/renderer/pages/navigator/instance/info/components/InstanceInfoValuesCard.tsx
  app/src/renderer/pages/navigator/instance/info/index.tsx
Labels: enhancement

#604 feat: close settings page on escape press
  app/src/renderer/layout/common/main-sidebar/navbar/SettingsMenu.tsx
Labels: enhancement

#606 fix: download update only allow once
  .changeset/fast-points-tan.md
  app/src/renderer/contexts/AppUpdatesContext.tsx
Labels: bug

#609 fix: add logfile error state
  app/src/renderer/lang/locales/en_US.ts
  app/src/renderer/pages/navigator/instance/logfile/index.tsx
Labels: bug

#629 fix: ResizeObserver loop limit exceeded error
  .changeset/modern-swans-remember.md
  app/package-lock.json
  app/package.json
Labels: bug

#632 fix: instance health refresh loading status
  app/src/renderer/hooks/useInstanceHealth.ts
Labels: bug

#633 chore: update dependencies minor version
  app/package-lock.json
  app/package.json
Labels: dependencies

#638 fix: implicit any error with auto sizer children
  app/src/renderer/components/menu/sidebar/Sidebar.tsx
  app/src/renderer/components/table/action/TableRowActionDetails.tsx
  app/src/renderer/layout/common/main-sidebar/MainSidebarLayout.tsx
  app/src/renderer/layout/common/secondary-sidebar/SecondarySidebarLayout.tsx
  app/src/renderer/layout/navigator/components/NavigatorSidebar.tsx
  app/src/renderer/layout/navigator/components/sidebar/tree/NavigatorTreePreview.tsx
  app/src/renderer/pages/navigator/home/components/HomeWhatsNew.tsx
Labels: bug

#639 fix: filter field type errors
  app/src/renderer/apis/requests/application/metric-rules/getApplicationMetricRules.ts
  app/src/renderer/apis/requests/crud/crudSearch.ts
  app/src/renderer/apis/requests/crud/types/crud-framework/crudFrameworkSearch.ts
  app/src/renderer/apis/requests/instance/heapdumps/getInstanceHeapdumpReferences.ts
  app/src/renderer/apis/requests/instance/thread-profiling/getInstanceThreadProfilingRequests.ts
Labels: bug
